"""empty message

Revision ID: 1936664ec33
Revises: 2345bfa569f
Create Date: 2015-11-22 21:13:44.596686

"""

# revision identifiers, used by Alembic.
revision = '1936664ec33'
down_revision = '2345bfa569f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nodes', sa.Column('motion_status', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nodes', 'motion_status')
    ### end Alembic commands ###
