"""empty message

Revision ID: 1d62d90de0d
Revises: 4aa2cf8b2af
Create Date: 2015-11-17 00:20:55.729379

"""

# revision identifiers, used by Alembic.
revision = '1d62d90de0d'
down_revision = '4aa2cf8b2af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
