"""empty message

Revision ID: 202f38341bd
Revises: a6f210d1c6
Create Date: 2015-11-17 15:32:01.027242

"""

# revision identifiers, used by Alembic.
revision = '202f38341bd'
down_revision = 'a6f210d1c6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('sched_type', sa.String(length=56), nullable=False))
    op.drop_column('rules', 'schedule_type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('schedule_type', sa.VARCHAR(length=56), autoincrement=False, nullable=False))
    op.drop_column('rules', 'sched_type')
    ### end Alembic commands ###
