"""empty message

Revision ID: 2345bfa569f
Revises: 202f38341bd
Create Date: 2015-11-22 20:49:52.248358

"""

# revision identifiers, used by Alembic.
revision = '2345bfa569f'
down_revision = '202f38341bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('turn_motion_on', sa.Boolean(), nullable=True))
    op.alter_column('rules', 'turn_on',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rules', 'turn_on',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_column('rules', 'turn_motion_on')
    ### end Alembic commands ###
