"""empty message

Revision ID: 32b5a65095e
Revises: 3a81028fee
Create Date: 2015-08-28 17:37:33.670336

"""

# revision identifiers, used by Alembic.
revision = '32b5a65095e'
down_revision = '3a81028fee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('reset_password_token', sa.String(length=100), server_default='', nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'username')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(length=35), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'reset_password_token')
    op.drop_column('users', 'confirmed_at')
    op.drop_column('users', 'active')
    ### end Alembic commands ###
