"""empty message

Revision ID: 418e9228da3
Revises: 5463d0d8aa
Create Date: 2015-11-03 08:51:30.686242

"""

# revision identifiers, used by Alembic.
revision = '418e9228da3'
down_revision = '5463d0d8aa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
