"""empty message

Revision ID: 4aa2cf8b2af
Revises: 3799f04aa3d
Create Date: 2015-11-17 00:10:26.281416

"""

# revision identifiers, used by Alembic.
revision = '4aa2cf8b2af'
down_revision = '3799f04aa3d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('event_node', sa.Integer(), nullable=True))
    op.add_column('rules', sa.Column('event_node_state', sa.Boolean(), nullable=True))
    op.add_column('rules', sa.Column('sched_hour', sa.Integer(), nullable=True))
    op.add_column('rules', sa.Column('sched_minute', sa.Integer(), nullable=True))
    op.add_column('rules', sa.Column('sched_time_of_day', sa.String(length=56), nullable=True))
    op.add_column('rules', sa.Column('sched_zip_code', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rules', 'nodes', ['event_node'], ['id'])
    op.drop_column('rules', 'minute')
    op.drop_column('rules', 'zip_code')
    op.drop_column('rules', 'time_of_day')
    op.drop_column('rules', 'hour')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('hour', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rules', sa.Column('time_of_day', sa.VARCHAR(length=56), autoincrement=False, nullable=True))
    op.add_column('rules', sa.Column('zip_code', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('rules', sa.Column('minute', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rules', type_='foreignkey')
    op.drop_column('rules', 'sched_zip_code')
    op.drop_column('rules', 'sched_time_of_day')
    op.drop_column('rules', 'sched_minute')
    op.drop_column('rules', 'sched_hour')
    op.drop_column('rules', 'event_node_state')
    op.drop_column('rules', 'event_node')
    ### end Alembic commands ###
