"""empty message

Revision ID: 5463d0d8aa
Revises: 32b5a65095e
Create Date: 2015-10-30 10:39:17.491069

"""

# revision identifiers, used by Alembic.
revision = '5463d0d8aa'
down_revision = '32b5a65095e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('turn_on', sa.Boolean(), nullable=False),
    sa.Column('days', sa.String(length=56), nullable=False),
    sa.Column('schedule_type', sa.String(length=56), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('zip_code', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.String(length=56), nullable=True),
    sa.Column('node', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['node'], ['nodes.id'], ),
    sa.PrimaryKeyConstraint('id', 'name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rules')
    ### end Alembic commands ###
