"""empty message

Revision ID: a6f210d1c6
Revises: 1d62d90de0d
Create Date: 2015-11-17 00:21:55.100054

"""

# revision identifiers, used by Alembic.
revision = 'a6f210d1c6'
down_revision = '1d62d90de0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
